name: Generate Snake

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: Platane/snk@v3
        with:
          github_user_name: bfabbio90
          outputs: snake.svg
      - name: Commit and push snake.svg
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add snake.svg
          git commit -m "Update snake graph" || echo "No changes to commit"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
